#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorE,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorD,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorF,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     Arm,           tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    Racky,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    r_tilt,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    l_tilt,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    Harvey2,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    Harvey1,              tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "armControlHeader.h"
#include "basic_move_header_autonomous.h"
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
task main()
{
	catcherTilt(0);
	servo[Harvey1]=127;
	servo[Harvey2]=127;
  goLow();
	moveShoulderUp(550);
	move_fwd(40,2000);
	wheel_stop();
	goLow();
	move_fwd(40,400);
	nMotorEncoder[Arm]=0;
	move_bck(40,200);
	moveShoulderUp(3100);
	catcherTilt(127);
	wait1Msec(1000);
	catcherTilt(255);
	wait1Msec(1000);
	move_fwd(40,240);
	wheel_stop();
	wait1Msec(750);
	servo[Harvey1] = 0;
	servo[Harvey2] = 255;
	wait1Msec(20000);
	/*while(SensorValue[touchSensor]==0){
		motor[Arm]=-10;
	}
	move_fwd(40,100);
	move_bck(40,110);
	motor[Arm]=20;
	wait1Msec(6500);
	motor[Arm]=0;
	move_fwd(40,100);
	servo[l_tilt]=255;
	servo[r_tilt]=0;
	wheel_stop();
	while(true){}
	/*while(SensorValue[touchSensor]==0){
		motor[Arm]=-10;
	}
	motor[Arm]=0;
	*/
}
